// src/components/Sidebar.vue
<template>
    <section class="sidebar w-100">
        <menu class="sidebar__menu list-none">
            <li>
                <a href="#" class="logo">
                    <svg class="x-icon" style="width: 100px; height: 25px">
                        <use href="assets/images/fx-SVG-sprite.svg#fx-logo"></use>
                    </svg>
                </a>
            </li>
            <li>
                <a href="#" class="sidebar__action" @click="newChat">New Chat ++</a>
            </li>
            <li>
                <a href="#" class="sidebar__action" @click="showHistory = true">History</a>
            </li>

            <li>
                <a href="#" class="sidebar__action" @click="showSettings = true">Settings</a>
            </li>
        </menu>

        <Drawer v-model:visible="showHistory" header="Chat History" :style="{ width: '400px' }">
            <fx-feed></fx-feed>
        </Drawer>
        <Drawer v-model:visible="showSettings" header="Settings" :style="{ width: '400px' }">
            <fx-settings></fx-settings>
        </Drawer>
    </section>
</template>
<script>
    import { ref, inject } from 'vue';
    import Drawer from 'primevue/drawer';
    export default {
        components: {
            Drawer,
        },
        setup() {
            const bus = inject('eventBus');
            const showHistory = ref(false);
            const showSettings = ref(false);

            const newChat = () => {
                // Logic to start a new chat
                bus.emit('new/chat');
                console.log('New chat started');
            };

            return {
                showHistory,
                showSettings,
                newChat,
            };
        },
    };
</script>

// src/components/Sidebar.jsx
import React, { useState, useContext } from 'react';
import { Sidebar as Drawer } from 'primereact/sidebar';
import eventBus from '@/services/busService';
// import FxFeed from '@/components/FxFeed';
import AppSettings from '@/components/Settings';

export default function Sidebar() {
    const [showHistory, setShowHistory] = useState(false);
    const [showSettings, setShowSettings] = useState(false);

    const newChat = () => {
        eventBus.emit('new/chat');
        console.log('New chat started');
    };

    return (
        <section className='sidebar w-100'>
            <menu className='sidebar__menu list-none'>
                <li>
                    <a href='#' className='logo' onClick={(e) => e.preventDefault()}>
                        <svg className='x-icon' style={{ width: '100px', height: '25px' }}>
                            <use href='assets/images/fx-SVG-sprite.svg#fx-logo' />
                        </svg>
                    </a>
                </li>
                <li>
                    <a
                        href='#'
                        className='sidebar__action'
                        onClick={(e) => {
                            e.preventDefault();
                            newChat();
                        }}
                    >
                        New Chat ++
                    </a>
                </li>
                <li>
                    <a
                        href='#'
                        className='sidebar__action'
                        onClick={(e) => {
                            e.preventDefault();
                            setShowHistory(true);
                        }}
                    >
                        History
                    </a>
                </li>
                <li>
                    <a
                        href='#'
                        className='sidebar__action'
                        onClick={(e) => {
                            e.preventDefault();
                            setShowSettings(true);
                        }}
                    >
                        Settings
                    </a>
                </li>
            </menu>

            <Drawer
                visible={showHistory}
                onHide={() => setShowHistory(false)}
                header='Chat History'
                position='left'
                style={{ width: '400px' }}
            ></Drawer>

            <Drawer
                visible={showSettings}
                onHide={() => setShowSettings(false)}
                header='Settings'
                position='left'
                style={{ width: '400px' }}
            >
                <AppSettings />
            </Drawer>
        </section>
    );
}
